version: '2'
services:
  web:
    # build: . # 相应镜像地址
    image: registry.cn-shenzhen.aliyuncs.com/yolanda/wsp_demo:sit
    command: /app/main
    ports:
      - 3005:3000
    restart: always
    environment:
      DATABASE_URL: mysql://root:1234@db/wsp
    depends_on:
      - db
  db:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
